/**
 * Kolay Asistan Medicine API
 * Kolay Asistan medicine application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMedicineApi);
  }
}(this, function(expect, KolayAsistanMedicineApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMedicineApi.FilterModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FilterModel', function() {
    it('should create an instance of FilterModel', function() {
      // uncomment below and update the code to test FilterModel
      //var instance = new KolayAsistanMedicineApi.FilterModel();
      //expect(instance).to.be.a(KolayAsistanMedicineApi.FilterModel);
    });

    it('should have the property page (base name: "page")', function() {
      // uncomment below and update the code to test the property page
      //var instance = new KolayAsistanMedicineApi.FilterModel();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new KolayAsistanMedicineApi.FilterModel();
      //expect(instance).to.be();
    });

    it('should have the property sort (base name: "sort")', function() {
      // uncomment below and update the code to test the property sort
      //var instance = new KolayAsistanMedicineApi.FilterModel();
      //expect(instance).to.be();
    });

    it('should have the property sortBy (base name: "sortBy")', function() {
      // uncomment below and update the code to test the property sortBy
      //var instance = new KolayAsistanMedicineApi.FilterModel();
      //expect(instance).to.be();
    });

    it('should have the property queryText (base name: "queryText")', function() {
      // uncomment below and update the code to test the property queryText
      //var instance = new KolayAsistanMedicineApi.FilterModel();
      //expect(instance).to.be();
    });

    it('should have the property searchBy (base name: "searchBy")', function() {
      // uncomment below and update the code to test the property searchBy
      //var instance = new KolayAsistanMedicineApi.FilterModel();
      //expect(instance).to.be();
    });

  });

}));
