/**
 * Kolay Asistan Medicine API
 * Kolay Asistan medicine application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMedicineApi);
  }
}(this, function(expect, KolayAsistanMedicineApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RequestTicketMedicine', function() {
    it('should create an instance of RequestTicketMedicine', function() {
      // uncomment below and update the code to test RequestTicketMedicine
      //var instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
      //expect(instance).to.be.a(KolayAsistanMedicineApi.RequestTicketMedicine);
    });

    it('should have the property fromCache (base name: "fromCache")', function() {
      // uncomment below and update the code to test the property fromCache
      //var instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
      //expect(instance).to.be();
    });

    it('should have the property ticketType (base name: "ticketType")', function() {
      // uncomment below and update the code to test the property ticketType
      //var instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
      //expect(instance).to.be();
    });

    it('should have the property barcode (base name: "barcode")', function() {
      // uncomment below and update the code to test the property barcode
      //var instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
      //expect(instance).to.be();
    });

    it('should have the property usePeriode (base name: "usePeriode")', function() {
      // uncomment below and update the code to test the property usePeriode
      //var instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
      //expect(instance).to.be();
    });

    it('should have the property usePeriodeUnit (base name: "usePeriodeUnit")', function() {
      // uncomment below and update the code to test the property usePeriodeUnit
      //var instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
      //expect(instance).to.be();
    });

    it('should have the property dailyUsingDose1 (base name: "dailyUsingDose1")', function() {
      // uncomment below and update the code to test the property dailyUsingDose1
      //var instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
      //expect(instance).to.be();
    });

    it('should have the property dailyUsingDose2 (base name: "dailyUsingDose2")', function() {
      // uncomment below and update the code to test the property dailyUsingDose2
      //var instance = new KolayAsistanMedicineApi.RequestTicketMedicine();
      //expect(instance).to.be();
    });

  });

}));
