/**
 * Kolay Asistan Medicine API
 * Kolay Asistan medicine application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KolayAsistanMedicineApi);
  }
}(this, function(expect, KolayAsistanMedicineApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KolayAsistanMedicineApi.Ticket();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Ticket', function() {
    it('should create an instance of Ticket', function() {
      // uncomment below and update the code to test Ticket
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be.a(KolayAsistanMedicineApi.Ticket);
    });

    it('should have the property medicineid (base name: "medicineid")', function() {
      // uncomment below and update the code to test the property medicineid
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property barcode (base name: "barcode")', function() {
      // uncomment below and update the code to test the property barcode
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property periodeKey (base name: "periodeKey")', function() {
      // uncomment below and update the code to test the property periodeKey
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property periodeValue (base name: "periodeValue")', function() {
      // uncomment below and update the code to test the property periodeValue
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property periodeFrequence (base name: "periodeFrequence")', function() {
      // uncomment below and update the code to test the property periodeFrequence
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property descriptionTr (base name: "description_tr")', function() {
      // uncomment below and update the code to test the property descriptionTr
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property descriptionEn (base name: "description_en")', function() {
      // uncomment below and update the code to test the property descriptionEn
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property descriptionRu (base name: "description_ru")', function() {
      // uncomment below and update the code to test the property descriptionRu
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property descriptionAr (base name: "description_ar")', function() {
      // uncomment below and update the code to test the property descriptionAr
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property from (base name: "from")', function() {
      // uncomment below and update the code to test the property from
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "imageUrl")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instance = new KolayAsistanMedicineApi.Ticket();
      //expect(instance).to.be();
    });

  });

}));
