/**
 * Kolay Asistan Medicine API
 * Kolay Asistan medicine application api layer. Revision Date: 04.12.2022
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ahmetyagibasan@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import FilterModel from './model/FilterModel';
import Medicine from './model/Medicine';
import RequestTicketMedicine from './model/RequestTicketMedicine';
import Ticket from './model/Ticket';
import DefaultApi from './api/DefaultApi';
import MedicineApi from './api/MedicineApi';
import TicketApi from './api/TicketApi';


/**
* Kolay Asistan medicine application api layer. Revision Date: 04.12.2022.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var KolayAsistanMedicineApi = require('index'); // See note below*.
* var xxxSvc = new KolayAsistanMedicineApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new KolayAsistanMedicineApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new KolayAsistanMedicineApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new KolayAsistanMedicineApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The FilterModel model constructor.
     * @property {module:model/FilterModel}
     */
    FilterModel,

    /**
     * The Medicine model constructor.
     * @property {module:model/Medicine}
     */
    Medicine,

    /**
     * The RequestTicketMedicine model constructor.
     * @property {module:model/RequestTicketMedicine}
     */
    RequestTicketMedicine,

    /**
     * The Ticket model constructor.
     * @property {module:model/Ticket}
     */
    Ticket,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The MedicineApi service constructor.
    * @property {module:api/MedicineApi}
    */
    MedicineApi,

    /**
    * The TicketApi service constructor.
    * @property {module:api/TicketApi}
    */
    TicketApi
};
